# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.19.2
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_version=1.2
maven_group=io.github.thevoidblock
archives_base_name = NoFortuneChest

# Dependencies
# check this on https://fabricmc.net/develop
fabric_api_version=0.150.0+26.1.2

# check this on https://linkie.shedaniel.dev
cloth_version=26.1.154
modmenu_version=18.0.0-beta.1
